### ISSUE TITLE
Is it possible to produce a diff without explicitly providing keys?

### ISSUE THREAD

**Issue by dpren** [benji6/virtual-audio-graph#29]
I'm wondering if you've thought about this.

Virtual DOMs can infer the identity of an element based on the surrounding tree structure. Would this be possible with graphs?

For context, I should mention I'm currently using your library in [dpren/elm-audio-graph](https://github.com/dpren/elm-audio-graph). I'd like to be able to pass nodes as values without assigning string/int keys.

**Comment by benji6** [comment]
Very interesting question! Well I know that while in general you are right about virtual DOM libs React does use keys when an element is in an array at least.

The problem seems to come down to how you describe connections between nodes. With the DOM you're dealing with a tree structure but with the audio graph you're dealing with a graph with directed edges. I can't really think of anyway you could specify this declaratively without using ids. If you have some ideas about how you want your API to look I'd love to see them and have a think about it. Awesome project by the way!

**Comment by dpren** [comment]
I'll let you know if I come up with anything. One interesting observation is that if you look at the graph backwards starting from AudioDestinationNode, ignoring cyclic connections, it's actually shaped like a tree. 🤔

**Comment by benji6** [comment]
Yeah that's true, you could build an API without ids if you only allowed for tree-like graphs, but it would be very limited compared to what you can actually do. Let me know if you come up with anything!

**Comment by benji6** [comment]
Hey @dpren I'm going to close this as it has been inactive for a while. Feel free to reopen if you have any new ideas :)
