### ISSUE TITLE
A custom node inside of a custom node

### ISSUE THREAD

**Issue by Nek** [benji6/virtual-audio-graph#317]
Hello @benji6,

I'm having another problem that could be a bug in the library.
I'm trying to extract setting a curve on a gain node into an AR component.
It looks like my code should work, but it doesn't. Please, take a look when you have some time for it.
This works:
https://codesandbox.io/s/relaxed-browser-lbhzz?file=/src/index.ts
This doesn't:
https://codesandbox.io/s/vibrant-buck-hlidp?file=/src/index.ts

Thanks! 
/Nik

**Comment by benji6** [comment]
Yep, this looks like a bug, will try to figure out what's going on here

**Comment by benji6** [comment]
There is actually one problem with your code example. If you connect to an custom audio node you need to specify which nodes within form the destination. So for your AR node it would have to look like this:

```js
const AR = createNode(({ A = 0, R = 0.5, gain: gainValue, startTime }) => {
  return {
    0: gain("output", {
      gain: [
        ["setValueAtTime", 0, startTime],
        ["linearRampToValueAtTime", gainValue, startTime + A],
        ["setValueAtTime", gainValue, startTime + A],
        ["linearRampToValueAtTime", 0, startTime + A + R]
      ],
    }, "input")
  };
});
```


There's a section in the documentation called "Custom Nodes With Inputs" which describes this https://virtual-audio-graph.netlify.app. The user has to specify which nodes are to be connected with because the library cannot work it out.

However, when I make that  change it seems to play some of the notes, but not all of them which is odd. I will do some more digging

**Comment by Nek** [comment]
Completely missed the input thing! Thanks a lot. I'll take a look into it too.

**Comment by benji6** [comment]
@Nek have pushed a new release, this was actually a regression in v1.1.7 (#316) - I've tested your code sandbox with the new version and it looks good

**Comment by Nek** [comment]
Thanks! I'll check it this weekend.
